const BrandData=[
    {
        id:1,
        img:"http://lezada.reactdemo.hasthemes.com/assets/images/brands/logo-2.png",
        brandName:"Nike",
        url:"/"
    },
    {
        id:2,
        img:"http://lezada.reactdemo.hasthemes.com/assets/images/brands/logo-1.png",
        brandName:"Nike",
        url:"/"
    },
    {
        id:3,
        img:"http://lezada.reactdemo.hasthemes.com/assets/images/brands/logo-3.png",
        brandName:"Nike",
        url:"/"
    },
    {
        id:4,
        img:"http://lezada.reactdemo.hasthemes.com/assets/images/brands/logo-4.png",
        brandName:"Nike",
        url:"/"
    },
    {
        id:5,
        img:"http://lezada.reactdemo.hasthemes.com/assets/images/brands/logo-5.png",
        brandName:"Nike",
        url:"/"
    },
    {
        id:6,
        img:"http://lezada.reactdemo.hasthemes.com/assets/images/brands/logo-6.png",
        brandName:"Nike",
        url:"/"
    },
]
export default BrandData